safe: true
encoding: UTF-8
url: https://roundcube.net
enforce_ssl: roundcube.net
hostname: "https://roundcube.net"
permalink: news/:year/:month/:day/:title
exclude: [vendor]
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/news/page:num/"
environment: "production"
num_related_items: 5
libs: {
    fonts: {
        roboto: 'https://fonts.googleapis.com/css?family=Roboto&amp;display=swap',
    },
    less: {
        url: 'https://cdn.jsdelivr.net/npm/less@4.5.1/dist/less.min.js',
        sri: 'sha384-MVgq3s6ICyRbsYSZ6lLQ8RQUIilNbZgTET5rBMnydd/ApxM/fvA41t+Z6i82Lcjn'
    },
    css: '/styles/styles.min.css?v=2024021800',
    bootstrap: {
        css: {
            url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css',
            sri: 'sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB'
        },
        js: {
            url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js',
            sri: 'sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI'
        }
    },
    fontawesome: {
        css: {
            url: 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@7.2.0/css/all.min.css',
            sri: 'sha384-EXatlQyrOJgDaM9/a74ArMzy7/2bTMSrZj8ID1IPeVmc3GncfCugefCFWSLj8JL/'
        },
    }
}
